### ISSUE TITLE
Add brightness and range settings

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/SurfaceLights#22]
* `brightness`  to set how significantly the light should illuminate the objects.
* `range` to define the max distance at which the objects get illuminated.

Open question: should these settings be available in flight?

**Comment by taksuda** [comment]
![1234](https://user-images.githubusercontent.com/29102678/63484714-cc8c2b00-c4df-11e9-983b-cf94afd5d29d.PNG)
can you also maybe add support to edit light colour in flight.  would be awesome. 
trying to make a display. using kos.
also no way I am gonna go change brightness settings one by one for all 450 lights.  in the vab. 
can you add that to in flight pls pls pls.

**Comment by ihsoft** [comment]
As far as I can tell, the issue in this case is not the brightness (or "intensity" in Unity terms). It's the light range. Now, it can be controlled (see: https://github.com/ihsoft/SurfaceLights/issues/4).
