### ISSUE TITLE
THIS IS A REQUEST. NOT A BUG!  inflight brightness settings?

### ISSUE THREAD

**Issue by taksuda** [ihsoft/SurfaceLights#23]
![jukvhjqyf9i31](https://user-images.githubusercontent.com/29102678/63631608-6cc18b80-c669-11e9-8adf-8ec563cddf0a.jpg)
wondering if this possible as I really really need it to make my display work. 
when a few lights on at ones display become saturated with light bleed. and everything become white washed. 

also regardless  we all  love you! at the kos community.  for awesome lights.

**Comment by ihsoft** [comment]
Addressed in scope of https://github.com/ihsoft/SurfaceLights/issues/22
