### ISSUE TITLE
Stock lights don't emit light, conflict with Restock

### ISSUE THREAD

**Issue by VasylMarchuk** [ihsoft/SurfaceLights#25]
Hello @ihsoft!

Restock recently updated to version 1.0 and this issue resurfaced again: https://github.com/ihsoft/SurfaceLights/issues/19

Stock lights don't project any light. Deleting `MM-StockLights.cfg` helps to get the lights working again but, on already launched vessels, all the custom colors get reset, and all the lights become white :(

**Comment by Taty095** [comment]
https://github.com/PorktoberRevolution/ReStocked/issues/761

**Comment by ihsoft** [comment]
I've figured the problem. It's about the order of MM patches. Will release the fix soon.
